name: tutorial
version: 1.0.0
dependencies:
 angular: "1.1.2"
 browser: ">=0.10.0+2 <0.11.0"
 polymer: ">=0.16.0 <0.17.0"
 firebase: '^0.6.3'
transformers:
- angular
- polymer:
   entry_points: web/index.html
